# Generated by Django 2.0.6 on 2018-06-13 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
